### ISSUE TITLE
Module 'collections' has no attribute 'Iterable'

### ISSUE THREAD

**Issue by pkkid** [jseutter/ofxparse#168]
This module is breaking on newer versions of Python because `collections.Iterable` is deprecated. It should be replaced with `collections.abc.Iterable`. See https://stackoverflow.com/questions/53978542/how-to-use-collections-abc-from-both-python-3-8-and-python-2-7/53978543#53978543

```python
Traceback (most recent call last):
  File "/home/pkkid/Projects/pushingkarma/pk/apps/budget/manager.py", line 140, in import_qfx
    qfx = OfxParser.parse(handle)
  File "/home/pkkid/Projects/pushingkarma/.direnv/python-3.10.4/lib/python3.10/site-packages/ofxparse/ofxparse.py", line 387, in parse
    ofx_file = OfxPreprocessedFile(file_handle)
  File "/home/pkkid/Projects/pushingkarma/.direnv/python-3.10.4/lib/python3.10/site-packages/ofxparse/ofxparse.py", line 147, in __init__
    super(OfxPreprocessedFile, self).__init__(fh)
  File "/home/pkkid/Projects/pushingkarma/.direnv/python-3.10.4/lib/python3.10/site-packages/ofxparse/ofxparse.py", line 65, in __init__
    if not is_iterable(self.fh):
  File "/home/pkkid/Projects/pushingkarma/.direnv/python-3.10.4/lib/python3.10/site-packages/ofxparse/ofxparse.py", line 40, in is_iterable
    return isinstance(candidate, collections.Iterable)
AttributeError: module 'collections' has no attribute 'Iterable'
```

**Comment by pkkid** [comment]
I was using an out of date version. This was fixed in version 0.21.
Sorry for the noise.
