### ISSUE TITLE
Empty tags

### ISSUE THREAD

**Issue by sanderkruger** [jseutter/ofxparse#81]
My bank exports files with empty tags here and there, for example:
<FI><ORG/><FID/></FI>

The empty tag syntax is valid XML but the parser doesn't like it. I can remove empty tags of course, but then I have to process all my bank statements. It would be much better if ofxparse sees the empty tag format and ignores the tags.

**Comment by nathangrigg** [comment]
After merging #108, the parser is more lenient. My guess is that this will go away. If you are able, could you check if this is still an issue?

**Comment by bruny** [comment]
I continue to see similar issues with ofxparse 0.18.

My bank has exported an OFX file with the following empty fields:
CHECKNUM, FITID, NAME, CURDEF, BRANCHID, ACCTTYPE, REFNUM

The stacktrace is
```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/bin/hledger-autosync", line 11, in <module>
    sys.exit(run())
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ledgerautosync/cli.py", line 311, in run
    import_ofx(ledger, args)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ledgerautosync/cli.py", line 114, in import_ofx
    ofx = OfxSynchronizer.parse_file(args.PATH)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ledgerautosync/sync.py", line 41, in parse_file
    return OfxParser.parse(open(path))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ofxparse/ofxparse.py", line 432, in parse
    ofx_obj.accounts += cls.parseStmtrs(stmtrs_ofx, AccountType.Bank)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ofxparse/ofxparse.py", line 818, in parseStmtrs
    account.curdef = act_curdef.contents[0].strip()
IndexError: list index out of range
```

**Comment by jseutter** [comment]
Some unit tests would be helpful to check for this behavior.  If I have time I'll create some.

**Comment by bruny** [comment]
I can add the OFX files I'm using as test cases on a PR. 2 x separate OFX files from Australian banks, both using version 1.02 (SGML!).

**Comment by bruny** [comment]
PR #143 added fixes for some elements, still some others to go.

**Comment by bruny** [comment]
Two sample STMTTRN entries, both using v1.02 spec:

```<STMTTRN>
 <TRNTYPE>Credit</TRNTYPE>
 <DTPOSTED>20180801</DTPOSTED>
 <TRNAMT>0.0</TRNAMT>
 <FITID></FITID>
 <VALUEDATE>20180801</VALUEDATE>
 <NAME></NAME>
 <TRANSACTIONSPLIT>No</TRANSACTIONSPLIT>
 <CATEGORY>Uncategorised</CATEGORY>
 <ACCTBAL>-400.52</ACCTBAL>
 <CHECKNUM></CHECKNUM>
 <REFNUM></REFNUM>
 <MEMO>NEW INTEREST RATE  3.870%</MEMO>
 <CURRENCY>
  <CURRATE>1.0000</CURRATE>
  <CURSYM>AUD</CURSYM>
 </CURRENCY>
</STMTTRN>```

and

```<STMTTRN>
<TRNTYPE>DEBIT
<DTPOSTED>20180801
<DTUSER>20180801
<TRNAMT>-10.00
<FITID>
<MEMO>Account Fee
</STMTTRN>```

Both have empty FITID fields. One has empty NAME field. Either empty or missing CHECKNUM and REFNUM fields.

Since transactions can be parsed by ofxparse if CHECKNUM, REFNAME, NAME and FITID are missing, empty fields should be handled in the same way.

Will try and put together a PR for these in the next few days.
